apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw3-cluster-deployment-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw3-app-label
  template:
    metadata:
      labels:
        app: hw3-app-label
    spec:
      containers:
        - name: hw3-container
          image: akshathphillipspersonal/swe645-hw3:v5
          ports:
            - containerPort: 8081  # Updated to 8081
---
apiVersion: v1
kind: Service
metadata:
  name: hw3-cluster-deployment
spec:
  type: NodePort
  selector:
    app: hw3-app-label
  ports:
    - protocol: TCP
      port: 8081  # Updated to 8081
      targetPort: 8081  # Updated to 8081
      name: http